name: include_dbt_sandbox
version: 1.0.0
profile: include_dbt_sandbox
model-paths:
- models
macro-paths:
- macros
seed-paths:
- seeds
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
vars: {}
models:
  +materialized: table
  include_dbt_sandbox:
    include:
      +tags: [study_stage,include]
      aadsc:
        +tags: [SD_ID_HERE, aadsc]
        src:
          +schema: inc_aadsc_src
        int:
          +schema: inc_aadsc_int
    kids_first:
      +tags: [study_stage,kids_first]
      sd_1nns3k8v:
        +tags: [sd_1nns3k8v,STUDY_SHORTCODE_HERE]
        src:
          +schema: kf_sd_1nns3k8v_src
        int:
          +schema: kf_sd_1nns3k8v_int
    access:
      +tags: [access_stage]
      +schema: access
    export:
      +tags: [export_stage]
      fhir:
        +tags: [fhir]
        +schema: fhir_export
    combined:
      +tags: [combined_stage]
      +schema: combined
