name: include_dbt_sandbox
version: 1.0.0
profile: include_dbt_sandbox
model-paths:
- models
macro-paths:
- macros
seed-paths:
- seeds
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
vars: {}
models:
  +materialized: table
  include_dbt_sandbox:
    include:
      aadsc:
        src:
          +schema: inc_aadsc_src
        int:
          +schema: inc_aadsc_int
    access:
      +schema: access
    export:
      fhir:
        +schema: fhir_export
    combined:
      +schema: combined
