---
include_dbt_sandbox:
  target: ci
  outputs:
    dev:
      dbname: postgres
      host: "{{ env_var('INCLUDEWAREHOUSE_HOST') }}"
      pass: "{{ env_var('INCLUDEWAREHOUSE_PASSWORD') }}"
      port: 5432
      schema: "{{ env_var('INCLUDEWAREHOUSE_DEV_SCHEMA_NAME') }}"
      threads: 4
      type: postgres
      user: "{{ env_var('INCLUDEWAREHOUSE_USERNAME') }}"
