{{ config(materialized='table') }}

    select
    ROW_NUMBER() OVER () AS "include_index",
    "MASKED_ID"::text as "masked_id",
    "AGE"::text as "age",
    "SEX"::text as "sex",
    "RACE"::text as "race",
    "ETHNICITY"::text as "ethnicity",
    "EXTRACTION_DATE"::text as "extraction_date",
    "BMI"::text as "bmi",
    "HEIGHT"::text as "height",
    "WEIGHT"::text as "weight",
    "Abnormalities of gait and mobility"::text as "abnormalities_of_gait_and_mobility",
    "Achalasia"::text as "achalasia",
    "Acute bronchitis"::text as "acute_bronchitis",
    "Acute kidney failure"::text as "acute_kidney_failure",
    "acute myocardial infarction"::text as "acute_myocardial_infarction",
    "Acute nasopharyngitis"::text as "acute_nasopharyngitis",
    "Acute recurrent sinusitis"::text as "acute_recurrent_sinusitis",
    "Acute sinusitis"::text as "acute_sinusitis",
    "All malignant neoplamsm"::text as "all_malignant_neoplamsm",
    "Allergic rhinitis"::text as "allergic_rhinitis",
    "Appendicitis"::text as "appendicitis",
    "Atherosclerotic heart disease of native coronary artery"::text as "atherosclerotic_heart_disease_of_native_coronary_artery",
    "auto_alopecia_status"::text as "auto_alopecia_status",
    "auto_arthropathy_status"::text as "auto_arthropathy_status",
    "auto_atopic_status"::text as "auto_atopic_status",
    "auto_celiac_status"::text as "auto_celiac_status",
    "auto_dermatomyositis_status"::text as "auto_dermatomyositis_status",
    "auto_graves_status"::text as "auto_graves_status",
    "auto_hashimoto_status"::text as "auto_hashimoto_status",
    "auto_hemol_anemia_status"::text as "auto_hemol_anemia_status",
    "auto_herpetiformis_status"::text as "auto_herpetiformis_status",
    "auto_hidradenitis_status"::text as "auto_hidradenitis_status",
    "auto_kawasaki_status"::text as "auto_kawasaki_status",
    "auto_menieres_status"::text as "auto_menieres_status",
    "auto_myositis_status"::text as "auto_myositis_status",
    "auto_narcolepsy_status"::text as "auto_narcolepsy_status",
    "auto_neutropenia_status"::text as "auto_neutropenia_status",
    "auto_other_specify"::text as "auto_other_specify",
    "auto_planus_status"::text as "auto_planus_status",
    "auto_psoriasis_status"::text as "auto_psoriasis_status",
    "auto_psoriatic_arth_status"::text as "auto_psoriatic_arth_status",
    "auto_rh_arthritis_status"::text as "auto_rh_arthritis_status",
    "auto_rls_status"::text as "auto_rls_status",
    "auto_sarcoidosis_status"::text as "auto_sarcoidosis_status",
    "auto_sclerosus_status"::text as "auto_sclerosus_status",
    "auto_sle_status"::text as "auto_sle_status",
    "auto_t1_diabetes_status"::text as "auto_t1_diabetes_status",
    "auto_thrombo_purpura_status"::text as "auto_thrombo_purpura_status",
    "cardiac_asd_age"::text as "cardiac_asd_age",
    "cardiac_cardiomyopathy_status"::text as "cardiac_cardiomyopathy_status",
    "cardiac_conditions"::text as "cardiac_conditions",
    "cardiac_congestive_status"::text as "cardiac_congestive_status",
    "cardiac_hypertension_status"::text as "cardiac_hypertension_status",
    "cardiac_mi_status"::text as "cardiac_mi_status",
    "cardiac_other_chd_specify"::text as "cardiac_other_chd_specify",
    "cardiac_other_specify"::text as "cardiac_other_specify",
    "cardiac_pda_age"::text as "cardiac_pda_age",
    "cardiac_pfo_age"::text as "cardiac_pfo_age",
    "cardiac_tof_age"::text as "cardiac_tof_age",
    "cardiac_vsd_age"::text as "cardiac_vsd_age",
    "Cerebrovascular diseases"::text as "cerebrovascular_diseases",
    "Cervical Myelopathy"::text as "cervical_myelopathy",
    "Change in skin texture"::text as "change_in_skin_texture",
    "cholesteatoma of external ear"::text as "cholesteatoma_of_external_ear",
    "Chronic cough"::text as "chronic_cough",
    "chronic ischemic heart diseases"::text as "chronic_ischemic_heart_diseases",
    "Chronic kidney disease"::text as "chronic_kidney_disease",
    "Chronic nasopharyngitis"::text as "chronic_nasopharyngitis",
    "Constipation"::text as "constipation",
    "develop_expressive_status"::text as "develop_expressive_status",
    "develop_mixed_status"::text as "develop_mixed_status",
    "Disorder of adrenal gland-unspecified"::text as "disorder_of_adrenal_gland_unspecified",
    "Do not resuscitate status"::text as "do_not_resuscitate_status",
    "ds_diagnosis"::text as "ds_diagnosis",
    "Dysmenorrhea"::text as "dysmenorrhea",
    "Dysphagia"::text as "dysphagia",
    "endo_congen_diabetes_status"::text as "endo_congen_diabetes_status",
    "endo_diabetes_conditions"::text as "endo_diabetes_conditions",
    "endo_graves_status"::text as "endo_graves_status",
    "endo_hyperthyroid_status"::text as "endo_hyperthyroid_status",
    "endo_hypothyroid_status"::text as "endo_hypothyroid_status",
    "endo_other_specify"::text as "endo_other_specify",
    "endo_t1_diabetes_status"::text as "endo_t1_diabetes_status",
    "endo_t2_diabetes_status"::text as "endo_t2_diabetes_status",
    "endo_thyroid_other_specify"::text as "endo_thyroid_other_specify",
    "endo_vitaminb_status"::text as "endo_vitaminb_status",
    "endo_vitamind_status"::text as "endo_vitamind_status",
    "ent_etd_status"::text as "ent_etd_status",
    "ent_hearing_status"::text as "ent_hearing_status",
    "ent_laryngo_status"::text as "ent_laryngo_status",
    "ent_osa_status"::text as "ent_osa_status",
    "ent_rhinitis_status"::text as "ent_rhinitis_status",
    "Esophagitis"::text as "esophagitis",
    "eye_amblyopia"::text as "eye_amblyopia",
    "eye_astigmatism"::text as "eye_astigmatism",
    "eye_blind"::text as "eye_blind",
    "eye_cataracts"::text as "eye_cataracts",
    "eye_glaucoma"::text as "eye_glaucoma",
    "eye_hyperopia"::text as "eye_hyperopia",
    "eye_keratoconus"::text as "eye_keratoconus",
    "eye_myopia"::text as "eye_myopia",
    "eye_nystagmus"::text as "eye_nystagmus",
    "eye_ptosis"::text as "eye_ptosis",
    "eye_retina"::text as "eye_retina",
    "eye_strabismus"::text as "eye_strabismus",
    "Fatty liver"::text as "fatty_liver",
    "female_pcos_status"::text as "female_pcos_status",
    "Follicular disorder"::text as "follicular_disorder",
    "gi_celiac_status"::text as "gi_celiac_status",
    "gi_diverticulitis_status"::text as "gi_diverticulitis_status",
    "gi_esophageal_atresia_status"::text as "gi_esophageal_atresia_status",
    "gi_gerd_status"::text as "gi_gerd_status",
    "gi_hemorrhoids_status"::text as "gi_hemorrhoids_status",
    "gi_hirschsprung_status"::text as "gi_hirschsprung_status",
    "gi_ibs_status"::text as "gi_ibs_status",
    "gi_other_specify"::text as "gi_other_specify",
    "gi_peptic_ulcers_status"::text as "gi_peptic_ulcers_status",
    "gi_pyloric_stenosis_status"::text as "gi_pyloric_stenosis_status",
    "heme_amkl_status"::text as "heme_amkl_status",
    "heme_aml_status"::text as "heme_aml_status",
    "heme_b_all_status"::text as "heme_b_all_status",
    "heme_leuk_rxn_status"::text as "heme_leuk_rxn_status",
    "heme_other_cancer_status"::text as "heme_other_cancer_status",
    "heme_other_specify"::text as "heme_other_specify",
    "heme_tmd_status"::text as "heme_tmd_status",
    "Hernia"::text as "hernia",
    "Impacted cerumen"::text as "impacted_cerumen",
    "infection_c_diff_status"::text as "infection_c_diff_status",
    "infection_cellulitis_status"::text as "infection_cellulitis_status",
    "infection_gout_status"::text as "infection_gout_status",
    "infection_impetigo_status"::text as "infection_impetigo_status",
    "infection_otitis_status"::text as "infection_otitis_status",
    "infection_periodontitis_status"::text as "infection_periodontitis_status",
    "infection_sinus_status"::text as "infection_sinus_status",
    "infection_tb_status"::text as "infection_tb_status",
    "infection_uti_status"::text as "infection_uti_status",
    "infection_zoster_status"::text as "infection_zoster_status",
    "lymph_anemia_status"::text as "lymph_anemia_status",
    "male_cancer_status"::text as "male_cancer_status",
    "male_hypospadias_status"::text as "male_hypospadias_status",
    "male_phimosis_status"::text as "male_phimosis_status",
    "male_testicles_status"::text as "male_testicles_status",
    "Metrorrhagia"::text as "metrorrhagia",
    "neuro_alz_status"::text as "neuro_alz_status",
    "neuro_dementia_status"::text as "neuro_dementia_status",
    "neuro_epilepsy_status"::text as "neuro_epilepsy_status",
    "neuro_moya_status"::text as "neuro_moya_status",
    "neuro_other_specify"::text as "neuro_other_specify",
    "neuro_palsy_status"::text as "neuro_palsy_status",
    "neuro_parkinson_status"::text as "neuro_parkinson_status",
    "Nonalcoholic steatohepatitis"::text as "nonalcoholic_steatohepatitis",
    "Onychomycosis"::text as "onychomycosis",
    "orthostatic hypotension"::text as "orthostatic_hypotension",
    "Overweight and Obesity"::text as "overweight_and_obesity",
    "psych_add_adhd_status"::text as "psych_add_adhd_status",
    "psych_anxiety_status"::text as "psych_anxiety_status",
    "psych_autism_status"::text as "psych_autism_status",
    "psych_bipolar_status"::text as "psych_bipolar_status",
    "psych_depression_status"::text as "psych_depression_status",
    "psych_ocd_status"::text as "psych_ocd_status",
    "psych_odd_status"::text as "psych_odd_status",
    "psych_other_specify"::text as "psych_other_specify",
    "psych_panic_status"::text as "psych_panic_status",
    "psych_ptsd_status"::text as "psych_ptsd_status",
    "psych_schizophrenia_status"::text as "psych_schizophrenia_status",
    "Psychiatric Disorders"::text as "psychiatric_disorders",
    "pulm_asthma_status"::text as "pulm_asthma_status",
    "pulm_other_specify"::text as "pulm_other_specify",
    "pulm_pulm_hypertension_status"::text as "pulm_pulm_hypertension_status",
    "skel_arthritis_status"::text as "skel_arthritis_status",
    "skel_osteoarthritis_status"::text as "skel_osteoarthritis_status",
    "skel_osteoporosis_status"::text as "skel_osteoporosis_status",
    "skel_scoliosis_status"::text as "skel_scoliosis_status",
    "skin_acne_age"::text as "skin_acne_age",
    "skin_acne_status"::text as "skin_acne_status",
    "skin_alopecia_age"::text as "skin_alopecia_age",
    "skin_alopecia_status"::text as "skin_alopecia_status",
    "skin_athlete_status"::text as "skin_athlete_status",
    "skin_atopic_status"::text as "skin_atopic_status",
    "skin_cellulitis_status"::text as "skin_cellulitis_status",
    "skin_hidradenitis_status"::text as "skin_hidradenitis_status",
    "skin_psoriasis_status"::text as "skin_psoriasis_status",
    "skin_rosacea_status"::text as "skin_rosacea_status",
    "skin_seborrheic_status"::text as "skin_seborrheic_status",
    "Spondylosis"::text as "spondylosis",
    "Tinea barbae and tinea capitis"::text as "tinea_barbae_and_tinea_capitis",
    "Tinea Cruris"::text as "tinea_cruris",
    "Unspecified blepharitis unspecified eye- unspecified eyelid"::text as "unspecified_blepharitis_unspecified_eye_unspecified_eyelid",
    "Urinary incontinence"::text as "urinary_incontinence",
    "Urinary retention"::text as "urinary_retention",
    "urogen_agenesis_status"::text as "urogen_agenesis_status",
    "urogen_hydroneph_status"::text as "urogen_hydroneph_status",
    "urogen_kidney_dz_status"::text as "urogen_kidney_dz_status",
    "urogen_kidney_status"::text as "urogen_kidney_status",
    "urogen_other_specify"::text as "urogen_other_specify",
    "urogen_reflux_status"::text as "urogen_reflux_status",
    "vitamin B12 deficiency"::text as "vitamin_b12_deficiency",
    "Vitamin D deficiency"::text as "vitamin_d_deficiency",
    "Xerosis cutis"::text as "xerosis_cutis"
    from {{ source('aadsc', 'chicoine_down_syndrome_extract') }}
    