sources:
- name: chr_18
  schema: kf_chr_18_src
  tables:
  - name: chr_18_phenotype_data
    description: Source table for chr_18_phenotype_data.
    columns:
    - name: Family ID
      description: '{{ doc("chr_18_phenotype_data_family_id") }}'
    - name: Participant ID
      description: '{{ doc("chr_18_phenotype_data_participant_id") }}'
    - name: Family Relationship Target Participant ID
      description: '{{ doc("chr_18_phenotype_data_family_relationship_target_pa_59d6df7d")
        }}'
    - name: alliquot_id
      description: '{{ doc("chr_18_phenotype_data_alliquot_id") }}'
    - name: Consent Group
      description: '{{ doc("chr_18_phenotype_data_consent_group") }}'
    - name: Age at Sample
      description: '{{ doc("chr_18_phenotype_data_age_at_sample") }}'
    - name: Sample Composition
      description: '{{ doc("chr_18_phenotype_data_sample_composition") }}'
    - name: Race
      description: '{{ doc("chr_18_phenotype_data_race") }}'
    - name: Sex
      description: '{{ doc("chr_18_phenotype_data_sex") }}'
    - name: Ethnicity
      description: '{{ doc("chr_18_phenotype_data_ethnicity") }}'
    - name: Analyte Type
      description: '{{ doc("chr_18_phenotype_data_analyte_type") }}'
    - name: Age at Phenotype
      description: '{{ doc("chr_18_phenotype_data_age_at_phenotype") }}'
    - name: Affected Status
      description: '{{ doc("chr_18_phenotype_data_affected_status") }}'
    - name: Vital Status
      description: '{{ doc("chr_18_phenotype_data_vital_status") }}'
    - name: chiari 2
      description: '{{ doc("chr_18_phenotype_data_chiari_2") }}'
    - name: pituitary gland abn
      description: '{{ doc("chr_18_phenotype_data_pituitary_gland_abn") }}'
    - name: cleft palate
      description: '{{ doc("chr_18_phenotype_data_cleft_palate") }}'
    - name: hearing loss
      description: '{{ doc("chr_18_phenotype_data_hearing_loss") }}'
    - name: tetralogy of fallot
      description: '{{ doc("chr_18_phenotype_data_tetralogy_of_fallot") }}'
    - name: conductive hearing loss
      description: '{{ doc("chr_18_phenotype_data_conductive_hearing_loss") }}'
    - name: holoprosencephaly
      description: '{{ doc("chr_18_phenotype_data_holoprosencephaly") }}'
    - name: choanal atresia
      description: '{{ doc("chr_18_phenotype_data_choanal_atresia") }}'
    - name: aural atresia
      description: '{{ doc("chr_18_phenotype_data_aural_atresia") }}'
    - name: midface hypoplasia
      description: '{{ doc("chr_18_phenotype_data_midface_hypoplasia") }}'
    - name: dysmyelination
      description: '{{ doc("chr_18_phenotype_data_dysmyelination") }}'
    - name: polymicrogyria
      description: '{{ doc("chr_18_phenotype_data_polymicrogyria") }}'
    - name: cryptorchidism
      description: '{{ doc("chr_18_phenotype_data_cryptorchidism") }}'
    - name: sensorineural hearing loss
      description: '{{ doc("chr_18_phenotype_data_sensorineural_hearing_loss") }}'
    - name: cleft lip
      description: '{{ doc("chr_18_phenotype_data_cleft_lip") }}'
    - name: imperforate anus
      description: '{{ doc("chr_18_phenotype_data_imperforate_anus") }}'
    - name: microcephaly
      description: '{{ doc("chr_18_phenotype_data_microcephaly") }}'
    - name: vertical talus
      description: '{{ doc("chr_18_phenotype_data_vertical_talus") }}'
    - name: hypospadias
      description: '{{ doc("chr_18_phenotype_data_hypospadias") }}'
    - name: rocker bottom foot
      description: '{{ doc("chr_18_phenotype_data_rocker_bottom_foot") }}'
    - name: chiari 1
      description: '{{ doc("chr_18_phenotype_data_chiari_1") }}'
    - name: ptosis
      description: '{{ doc("chr_18_phenotype_data_ptosis") }}'
    - name: strabismus
      description: '{{ doc("chr_18_phenotype_data_strabismus") }}'
    - name: bilateral coxa valga
      description: '{{ doc("chr_18_phenotype_data_bilateral_coxa_valga") }}'
    - name: cardiac_nos
      description: '{{ doc("chr_18_phenotype_data_cardiac_nos") }}'
    - name: corpus callosum abn
      description: '{{ doc("chr_18_phenotype_data_corpus_callosum_abn") }}'
    - name: pulmonary valve stenosis
      description: '{{ doc("chr_18_phenotype_data_pulmonary_valve_stenosis") }}'
    - name: metatarsus varus
      description: '{{ doc("chr_18_phenotype_data_metatarsus_varus") }}'
    - name: decreased white matter volume
      description: '{{ doc("chr_18_phenotype_data_decreased_white_matter_volume")
        }}'
    - name: macrocephaly
      description: '{{ doc("chr_18_phenotype_data_macrocephaly") }}'
    - name: suprasellar cyst
      description: '{{ doc("chr_18_phenotype_data_suprasellar_cyst") }}'
    - name: hydrocephalus
      description: '{{ doc("chr_18_phenotype_data_hydrocephalus") }}'
    - name: micropenis
      description: '{{ doc("chr_18_phenotype_data_micropenis") }}'
    - name: anal stenosis
      description: '{{ doc("chr_18_phenotype_data_anal_stenosis") }}'
    - name: congenital heart malformation
      description: '{{ doc("chr_18_phenotype_data_congenital_heart_malformation")
        }}'
    - name: bilateral choanal atresia
      description: '{{ doc("chr_18_phenotype_data_bilateral_choanal_atresia") }}'
    - name: dandy walker malformation
      description: '{{ doc("chr_18_phenotype_data_dandy_walker_malformation") }}'
    - name: dandy walker
      description: '{{ doc("chr_18_phenotype_data_dandy_walker") }}'
    - name: congenital heart defect
      description: '{{ doc("chr_18_phenotype_data_congenital_heart_defect") }}'
    - name: aural stenosis
      description: '{{ doc("chr_18_phenotype_data_aural_stenosis") }}'
    - name: kidney malform
      description: '{{ doc("chr_18_phenotype_data_kidney_malform") }}'
    - name: pituitary fossa enlargement
      description: '{{ doc("chr_18_phenotype_data_pituitary_fossa_enlargement") }}'
    - name: submucous cleft
      description: '{{ doc("chr_18_phenotype_data_submucous_cleft") }}'
    - name: virchow robins spaces
      description: '{{ doc("chr_18_phenotype_data_virchow_robins_spaces") }}'
    - name: retinal coloboma
      description: '{{ doc("chr_18_phenotype_data_retinal_coloboma") }}'
    - name: corneal staphyloma
      description: '{{ doc("chr_18_phenotype_data_corneal_staphyloma") }}'
    - name: club foot
      description: '{{ doc("chr_18_phenotype_data_club_foot") }}'
    - name: macroglossia
      description: '{{ doc("chr_18_phenotype_data_macroglossia") }}'
    - name: dandy walker variant
      description: '{{ doc("chr_18_phenotype_data_dandy_walker_variant") }}'
    - name: coanal atresia
      description: '{{ doc("chr_18_phenotype_data_coanal_atresia") }}'
    - name: occipatal lobe abn
      description: '{{ doc("chr_18_phenotype_data_occipatal_lobe_abn") }}'
    - name: asd
      description: '{{ doc("chr_18_phenotype_data_asd") }}'
    - name: vsd
      description: '{{ doc("chr_18_phenotype_data_vsd") }}'
    - name: pectus excavatum
      description: '{{ doc("chr_18_phenotype_data_pectus_excavatum") }}'
    - name: peripherial pulmonary stenosis
      description: '{{ doc("chr_18_phenotype_data_peripherial_pulmonary_stenosis")
        }}'
    - name: sagittal stenosis
      description: '{{ doc("chr_18_phenotype_data_sagittal_stenosis") }}'
    - name: hydronephrosis
      description: '{{ doc("chr_18_phenotype_data_hydronephrosis") }}'
    - name: patent ductus arteriosus
      description: '{{ doc("chr_18_phenotype_data_patent_ductus_arteriosus") }}'
    - name: duanes syndrome
      description: '{{ doc("chr_18_phenotype_data_duanes_syndrome") }}'
    - name: laryngomalacia
      description: '{{ doc("chr_18_phenotype_data_laryngomalacia") }}'
    - name: metatarsus adductus
      description: '{{ doc("chr_18_phenotype_data_metatarsus_adductus") }}'
    - name: ptosisbilateral
      description: '{{ doc("chr_18_phenotype_data_ptosisbilateral") }}'
    - name: microphallus
      description: '{{ doc("chr_18_phenotype_data_microphallus") }}'
    - name: sacral agenesis
      description: '{{ doc("chr_18_phenotype_data_sacral_agenesis") }}'
    - name: situs inversus
      description: '{{ doc("chr_18_phenotype_data_situs_inversus") }}'
    - name: Sample Tissue Type
      description: '{{ doc("chr_18_phenotype_data_sample_tissue_type") }}'
  - name: terra_manifest_v2
    description: Source table for terra_manifest_v2.
    columns:
    - name: entity:sample_id
      description: '{{ doc("terra_manifest_v2_entity_sample_id") }}'
    - name: project
      description: '{{ doc("terra_manifest_v2_project") }}'
    - name: collaborator_sample_id
      description: '{{ doc("terra_manifest_v2_collaborator_sample_id") }}'
    - name: version
      description: '{{ doc("terra_manifest_v2_version") }}'
    - name: data_type
      description: '{{ doc("terra_manifest_v2_data_type") }}'
    - name: pdo
      description: '{{ doc("terra_manifest_v2_pdo") }}'
    - name: release_date
      description: '{{ doc("terra_manifest_v2_release_date") }}'
    - name: reference_sequence_name
      description: '{{ doc("terra_manifest_v2_reference_sequence_name") }}'
    - name: collaborator_participant_id
      description: '{{ doc("terra_manifest_v2_collaborator_participant_id") }}'
    - name: cram_path
      description: '{{ doc("terra_manifest_v2_cram_path") }}'
    - name: crai_path
      description: '{{ doc("terra_manifest_v2_crai_path") }}'
    - name: md5_path
      description: '{{ doc("terra_manifest_v2_md5_path") }}'
    - name: root_sample_id
      description: '{{ doc("terra_manifest_v2_root_sample_id") }}'
    - name: mean_coverage
      description: '{{ doc("terra_manifest_v2_mean_coverage") }}'
    - name: adapter_rate
      description: '{{ doc("terra_manifest_v2_adapter_rate") }}'
    - name: pf_hq_aligned_q20_bases
      description: '{{ doc("terra_manifest_v2_pf_hq_aligned_q20_bases") }}'
    - name: pf_hq_aligned_reads
      description: '{{ doc("terra_manifest_v2_pf_hq_aligned_reads") }}'
    - name: pf_mismatch_rate
      description: '{{ doc("terra_manifest_v2_pf_mismatch_rate") }}'
    - name: pf_noise_reads
      description: '{{ doc("terra_manifest_v2_pf_noise_reads") }}'
    - name: pf_reads
      description: '{{ doc("terra_manifest_v2_pf_reads") }}'
    - name: pf_reads_aligned
      description: '{{ doc("terra_manifest_v2_pf_reads_aligned") }}'
    - name: total_reads
      description: '{{ doc("terra_manifest_v2_total_reads") }}'
    - name: mean_read_length
      description: '{{ doc("terra_manifest_v2_mean_read_length") }}'
    - name: pf_reads_rate
      description: '{{ doc("terra_manifest_v2_pf_reads_rate") }}'
    - name: pf_reads_aligned_rate
      description: '{{ doc("terra_manifest_v2_pf_reads_aligned_rate") }}'
    - name: pf_aligned_bases
      description: '{{ doc("terra_manifest_v2_pf_aligned_bases") }}'
    - name: reads_aligned_in_pairs
      description: '{{ doc("terra_manifest_v2_reads_aligned_in_pairs") }}'
    - name: contamination_rate
      description: '{{ doc("terra_manifest_v2_contamination_rate") }}'
    - name: genome_territory
      description: '{{ doc("terra_manifest_v2_genome_territory") }}'
    - name: exc_baseq_rate
      description: '{{ doc("terra_manifest_v2_exc_baseq_rate") }}'
    - name: exc_dupe_rate
      description: '{{ doc("terra_manifest_v2_exc_dupe_rate") }}'
    - name: exc_mapq_rate
      description: '{{ doc("terra_manifest_v2_exc_mapq_rate") }}'
    - name: exc_overlap_rate
      description: '{{ doc("terra_manifest_v2_exc_overlap_rate") }}'
    - name: 10x_rate
      description: '{{ doc("terra_manifest_v2_10x_rate") }}'
    - name: 20x_rate
      description: '{{ doc("terra_manifest_v2_20x_rate") }}'
    - name: exc_total_rate
      description: '{{ doc("terra_manifest_v2_exc_total_rate") }}'
    - name: exc_unpaired_rate
      description: '{{ doc("terra_manifest_v2_exc_unpaired_rate") }}'
    - name: chimera_rate
      description: '{{ doc("terra_manifest_v2_chimera_rate") }}'
    - name: het_snp_q
      description: '{{ doc("terra_manifest_v2_het_snp_q") }}'
    - name: het_snp_sensitivity
      description: '{{ doc("terra_manifest_v2_het_snp_sensitivity") }}'
    - name: library-1_estimated_library_size
      description: '{{ doc("terra_manifest_v2_library-1_estimated_library_size") }}'
    - name: library-1_mean_insert_size
      description: '{{ doc("terra_manifest_v2_library-1_mean_insert_size") }}'
    - name: library-1_name
      description: '{{ doc("terra_manifest_v2_library-1_pair_orientation") }}'
    - name: library-1_pct_exc_dupe
      description: '{{ doc("terra_manifest_v2_library-1_pct_exc_dupe") }}'
    - name: library-1_percent_duplication
      description: '{{ doc("terra_manifest_v2_library-1_percent_duplication") }}'
    - name: library-1_read_pairs
      description: '{{ doc("terra_manifest_v2_library-1_read_pairs") }}'
    - name: mean_insert_size
      description: '{{ doc("terra_manifest_v2_mean_insert_size") }}'
    - name: median_coverage
      description: '{{ doc("terra_manifest_v2_median_coverage") }}'
    - name: median_insert_size
      description: '{{ doc("terra_manifest_v2_median_insert_size") }}'
    - name: pf_hq_aligned_bases
      description: '{{ doc("terra_manifest_v2_pf_hq_aligned_bases") }}'
    - name: pf_hq_error_rate
      description: '{{ doc("terra_manifest_v2_pf_hq_error_rate") }}'
    - name: pf_reads_improper_pairs
      description: '{{ doc("terra_manifest_v2_pf_reads_improper_pairs") }}'
    - name: read_pair_duplicates
      description: '{{ doc("terra_manifest_v2_read_pair_duplicates") }}'
    - name: read_pair_optical_duplicates
      description: '{{ doc("terra_manifest_v2_read_pair_optical_duplicates") }}'
    - name: reads_aligned_in_pairs_rate
      description: '{{ doc("terra_manifest_v2_reads_aligned_in_pairs_rate") }}'
    - name: sample
      description: '{{ doc("terra_manifest_v2_sample") }}'
    - name: strand_balance
      description: '{{ doc("terra_manifest_v2_strand_balance") }}'
    - name: width_of_10_percent
      description: '{{ doc("terra_manifest_v2_width_of_10_percent") }}'
    - name: width_of_50_percent
      description: '{{ doc("terra_manifest_v2_width_of_50_percent") }}'
    - name: width_of_99_percent
      description: '{{ doc("terra_manifest_v2_width_of_99_percent") }}'
  - name: s3_scrape_cody
    description: Source table for s3_scrape_cody.
    columns:
    - name: Size
      description: '{{ doc("s3_scrape_cody_size") }}'
    - name: Key
      description: '{{ doc("s3_scrape_cody_key") }}'
    - name: ETag
      description: '{{ doc("s3_scrape_cody_etag") }}'
    - name: Bucket
      description: '{{ doc("s3_scrape_cody_bucket") }}'
    - name: LastModified
      description: '{{ doc("s3_scrape_cody_lastmodified") }}'
    - name: StorageClass
      description: '{{ doc("s3_scrape_cody_storageclass") }}'
