{{ config(materialized='table') }}

    select
    ROW_NUMBER() OVER () AS kf_index,
    "Family ID"::text as family_id,
    "Participant ID"::text as participant_id,
    "Family Relationship Target Participant ID"::text as family_relationship_target_participant_id,
    "alliquot_id"::text as aliquot_id,
    "Consent Group"::text as consent_group,
    "Age at Sample"::text as age_at_sample,
    "Sample Composition"::text as sample_composition,
    "Race"::text as race,
    "Sex"::text as sex,
    "Ethnicity"::text as ethnicity,
    "Analyte Type"::text as analyte_type,
    "Age at Phenotype"::text as age_at_phenotype,
    "Affected Status"::text as affected_status,
    "Vital Status"::text as vital_status,
    "chiari 2"::text as chiari_2,
    "pituitary gland abn"::text as pituitary_gland_abn,
    "cleft palate"::text as cleft_palate,
    "hearing loss"::text as hearing_loss,
    "tetralogy of fallot"::text as tetralogy_of_fallot,
    "conductive hearing loss"::text as conductive_hearing_loss,
    "holoprosencephaly"::text as holoprosencephaly,
    "choanal atresia"::text as choanal_atresia,
    "aural atresia"::text as aural_atresia,
    "midface hypoplasia"::text as midface_hypoplasia,
    "dysmyelination"::text as dysmyelination,
    "polymicrogyria"::text as polymicrogyria,
    "cryptorchidism"::text as cryptorchidism,
    "sensorineural hearing loss"::text as sensorineural_hearing_loss,
    "cleft lip"::text as cleft_lip,
    "imperforate anus"::text as imperforate_anus,
    "microcephaly"::text as microcephaly,
    "vertical talus"::text as vertical_talus,
    "hypospadias"::text as hypospadias,
    "rocker bottom foot"::text as rocker_bottom_foot,
    "chiari 1"::text as chiari_1,
    "ptosis"::text as ptosis,
    "strabismus"::text as strabismus,
    "bilateral coxa valga"::text as bilateral_coxa_valga,
    "cardiac_nos"::text as cardiac_nos,
    "corpus callosum abn"::text as corpus_callosum_abn,
    "pulmonary valve stenosis"::text as pulmonary_valve_stenosis,
    "metatarsus varus"::text as metatarsus_varus,
    "decreased white matter volume"::text as decreased_white_matter_volume,
    "macrocephaly"::text as macrocephaly,
    "suprasellar cyst"::text as suprasellar_cyst,
    "hydrocephalus"::text as hydrocephalus,
    "micropenis"::text as micropenis,
    "anal stenosis"::text as anal_stenosis,
    "congenital heart malformation"::text as congenital_heart_malformation,
    "bilateral choanal atresia"::text as bilateral_choanal_atresia,
    "dandy walker malformation"::text as dandy_walker_malformation,
    "dandy walker"::text as dandy_walker,
    "congenital heart defect"::text as congenital_heart_defect,
    "aural stenosis"::text as aural_stenosis,
    "kidney malform"::text as kidney_malform,
    "pituitary fossa enlargement"::text as pituitary_fossa_enlargement,
    "submucous cleft"::text as submucous_cleft,
    "virchow robins spaces"::text as virchow_robins_spaces,
    "retinal coloboma"::text as retinal_coloboma,
    "corneal staphyloma"::text as corneal_staphyloma,
    "club foot"::text as club_foot,
    "macroglossia"::text as macroglossia,
    "dandy walker variant"::text as dandy_walker_variant,
    "coanal atresia"::text as coanal_atresia,
    "occipatal lobe abn"::text as occipatal_lobe_abn,
    "asd"::text as asd,
    "vsd"::text as vsd,
    "pectus excavatum"::text as pectus_excavatum,
    "peripherial pulmonary stenosis"::text as peripherial_pulmonary_stenosis,
    "sagittal stenosis"::text as sagittal_stenosis,
    "hydronephrosis"::text as hydronephrosis,
    "patent ductus arteriosus"::text as patent_ductus_arteriosus,
    "duanes syndrome"::text as duanes_syndrome,
    "laryngomalacia"::text as laryngomalacia,
    "metatarsus adductus"::text as metatarsus_adductus,
    "ptosisbilateral"::text as ptosisbilateral,
    "microphallus"::text as microphallus,
    "sacral agenesis"::text as sacral_agenesis,
    "situs inversus"::text as situs_inversus,
    "Sample Tissue Type"::text as sample_tissue_type
    from {{ source('chr_18', 'chr_18_phenotype_data') }}
    