#!/bin/bash
set -e
dbt clean
dbt deps || { echo "Error: dbt deps failed. Exiting..."; exit 1; }
dbt seed #--full-refresh
# Source tables
dbt run --select inc_brainpower_src_bp_age_event_latency
dbt run --select inc_brainpower_src_bp_anthropometrics
dbt run --select inc_brainpower_src_bp_cognitive_function
dbt run --select inc_brainpower_src_bp_imaging
dbt run --select inc_brainpower_src_bp_physical_activity_day
dbt run --select inc_brainpower_src_bp_physical_activity_person
dbt run --select inc_brainpower_src_bp_randomization
dbt run --select inc_brainpower_src_bp_demographics
dbt run --select inc_brainpower_src_bp_health_conditions
dbt run --select inc_brainpower_src_bp_oxygen_kinetics_meta
dbt run --select inc_brainpower_src_bp_oxygen_kinetics_group
# Stable tables
dbt run --select inc_brainpower_stb_accesspolicy
dbt run --select inc_brainpower_stb_activitydefinition
dbt run --select inc_brainpower_stb_activitydefinition_external_id
dbt run --select inc_brainpower_stb_aliquot
dbt run --select inc_brainpower_stb_aliquot_external_id
dbt run --select inc_brainpower_stb_biospecimencollection
dbt run --select inc_brainpower_stb_biospecimencollection_external_id
dbt run --select inc_brainpower_stb_concept
dbt run --select inc_brainpower_stb_doi
dbt run --select inc_brainpower_stb_doi_external_id
dbt run --select inc_brainpower_stb_dataset
dbt run --select inc_brainpower_stb_dataset_file_id
dbt run --select inc_brainpower_stb_dataset_publication
dbt run --select inc_brainpower_stb_demographics
dbt run --select inc_brainpower_stb_demographics_external_id
dbt run --select inc_brainpower_stb_demographics_race
dbt run --select inc_brainpower_stb_encounter
dbt run --select inc_brainpower_stb_encounterdefinition
dbt run --select inc_brainpower_stb_encounterdefinition_activity_definition_id
dbt run --select inc_brainpower_stb_encounterdefinition_external_id
dbt run --select inc_brainpower_stb_encounter_external_id
dbt run --select inc_brainpower_stb_family
dbt run --select inc_brainpower_stb_familymember
dbt run --select inc_brainpower_stb_familymember_external_id
dbt run --select inc_brainpower_stb_familyrelationship
dbt run --select inc_brainpower_stb_familyrelationship_external_id
dbt run --select inc_brainpower_stb_family_external_id
dbt run --select inc_brainpower_stb_file
dbt run --select inc_brainpower_stb_filehash
dbt run --select inc_brainpower_stb_file_external_id
dbt run --select inc_brainpower_stb_file_sample_id
dbt run --select inc_brainpower_stb_file_subject_id
dbt run --select inc_brainpower_stb_investigator
dbt run --select inc_brainpower_stb_investigator_external_id
dbt run --select inc_brainpower_stb_publication
dbt run --select inc_brainpower_stb_publication_external_id
dbt run --select inc_brainpower_stb_record_external_id
dbt run --select inc_brainpower_stb_sample
dbt run --select inc_brainpower_stb_sample_external_id
dbt run --select inc_brainpower_stb_sample_processing
dbt run --select inc_brainpower_stb_sample_storage_method
dbt run --select inc_brainpower_stb_study
dbt run --select inc_brainpower_stb_studymetadata
dbt run --select inc_brainpower_stb_studymetadata_clinical_data_source_type
dbt run --select inc_brainpower_stb_studymetadata_data_category
dbt run --select inc_brainpower_stb_studymetadata_external_id
dbt run --select inc_brainpower_stb_studymetadata_participant_lifespan_stage
dbt run --select inc_brainpower_stb_studymetadata_research_domain
dbt run --select inc_brainpower_stb_studymetadata_study_design
dbt run --select inc_brainpower_stb_study_clinical_data_source_type
dbt run --select inc_brainpower_stb_study_contact
dbt run --select inc_brainpower_stb_study_data_category
dbt run --select inc_brainpower_stb_study_external_id
dbt run --select inc_brainpower_stb_study_funding_source
dbt run --select inc_brainpower_stb_study_participant_lifespan_stage
dbt run --select inc_brainpower_stb_study_principal_investigator
dbt run --select inc_brainpower_stb_study_program
dbt run --select inc_brainpower_stb_study_publication
dbt run --select inc_brainpower_stb_study_research_domain
dbt run --select inc_brainpower_stb_study_study_design
dbt run --select inc_brainpower_stb_subject
dbt run --select inc_brainpower_stb_subjectassertion
dbt run --select inc_brainpower_stb_subjectassertion_concept
dbt run --select inc_brainpower_stb_subjectassertion_external_id
dbt run --select inc_brainpower_stb_subjectassertion_value_concept
dbt run --select inc_brainpower_stb_subject_external_id
dbt run --select inc_brainpower_stb_virtualbiorepository
dbt run --select inc_brainpower_stb_virtualbiorepository_contact
dbt run --select inc_brainpower_stb_virtualbiorepository_external_id
# Combined tables
dbt run --select combined_accesspolicy
dbt run --select combined_activitydefinition
dbt run --select combined_activitydefinition_external_id
dbt run --select combined_aliquot
dbt run --select combined_aliquot_external_id
dbt run --select combined_biospecimencollection
dbt run --select combined_biospecimencollection_external_id
dbt run --select combined_concept
dbt run --select combined_doi
dbt run --select combined_doi_external_id
dbt run --select combined_dataset
dbt run --select combined_dataset_file_id
dbt run --select combined_dataset_publication
dbt run --select combined_demographics
dbt run --select combined_demographics_external_id
dbt run --select combined_demographics_race
dbt run --select combined_encounter
dbt run --select combined_encounterdefinition
dbt run --select combined_encounterdefinition_activity_definition_id
dbt run --select combined_encounterdefinition_external_id
dbt run --select combined_encounter_external_id
dbt run --select combined_family
dbt run --select combined_familymember
dbt run --select combined_familymember_external_id
dbt run --select combined_familyrelationship
dbt run --select combined_familyrelationship_external_id
dbt run --select combined_family_external_id
dbt run --select combined_file
dbt run --select combined_filehash
dbt run --select combined_file_external_id
dbt run --select combined_file_sample_id
dbt run --select combined_file_subject_id
dbt run --select combined_investigator
dbt run --select combined_investigator_external_id
dbt run --select combined_publication
dbt run --select combined_publication_external_id
dbt run --select combined_record_external_id
dbt run --select combined_sample
dbt run --select combined_sample_external_id
dbt run --select combined_sample_processing
dbt run --select combined_sample_storage_method
dbt run --select combined_study
dbt run --select combined_studymetadata
dbt run --select combined_studymetadata_clinical_data_source_type
dbt run --select combined_studymetadata_data_category
dbt run --select combined_studymetadata_external_id
dbt run --select combined_studymetadata_participant_lifespan_stage
dbt run --select combined_studymetadata_research_domain
dbt run --select combined_studymetadata_study_design
dbt run --select combined_study_clinical_data_source_type
dbt run --select combined_study_contact
dbt run --select combined_study_data_category
dbt run --select combined_study_external_id
dbt run --select combined_study_funding_source
dbt run --select combined_study_participant_lifespan_stage
dbt run --select combined_study_principal_investigator
dbt run --select combined_study_program
dbt run --select combined_study_publication
dbt run --select combined_study_research_domain
dbt run --select combined_study_study_design
dbt run --select combined_subject
dbt run --select combined_subjectassertion
dbt run --select combined_subjectassertion_concept
dbt run --select combined_subjectassertion_external_id
dbt run --select combined_subjectassertion_value_concept
dbt run --select combined_subject_external_id
dbt run --select combined_virtualbiorepository
dbt run --select combined_virtualbiorepository_contact
dbt run --select combined_virtualbiorepository_external_id
# Export tables
dbt run --select fhir_accesspolicy
dbt run --select fhir_accesspolicy_access_policy_code
dbt run --select fhir_ageat
dbt run --select fhir_aliquot
dbt run --select fhir_aliquot_external_id
dbt run --select fhir_associatedparty
dbt run --select fhir_associatedparty_classifier
dbt run --select fhir_associatedparty_period_id
dbt run --select fhir_family
dbt run --select fhir_familyrelationship
dbt run --select fhir_family_external_id
dbt run --select fhir_filelocation
dbt run --select fhir_filemetadata
dbt run --select fhir_filemetadata_samples
dbt run --select fhir_hasexternalid_external_id
dbt run --select fhir_institution
dbt run --select fhir_institution_external_id
dbt run --select fhir_ncpifile
dbt run --select fhir_ncpifile_external_id
dbt run --select fhir_ncpifile_file_location_id
dbt run --select fhir_ncpifile_file_meta_data_id
dbt run --select fhir_participant
dbt run --select fhir_participantassertion
dbt run --select fhir_participant_external_id
dbt run --select fhir_participant_race
dbt run --select fhir_participant_sample_id
dbt run --select fhir_period
dbt run --select fhir_person
dbt run --select fhir_person_participant_id
dbt run --select fhir_practitioner
dbt run --select fhir_practitionerrole
dbt run --select fhir_practitioner_external_id
dbt run --select fhir_relativedatetime
dbt run --select fhir_researchstudy
dbt run --select fhir_researchstudycollection
dbt run --select fhir_researchstudycollection_external_id
dbt run --select fhir_researchstudycollection_label
dbt run --select fhir_researchstudycollection_research_study_collection_member_id
dbt run --select fhir_researchstudy_external_id
dbt run --select fhir_researchstudy_study_acknowledgement
dbt run --select fhir_researchstudy_study_condition
dbt run --select fhir_researchstudy_study_design
dbt run --select fhir_researchstudy_study_focus
dbt run --select fhir_researchstudy_study_personnel
dbt run --select fhir_researchsubject
dbt run --select fhir_sample
dbt run --select fhir_sample_external_id
dbt run --select fhir_sample_processing
dbt run --select fhir_studymembership
